# --- Imagen base
FROM debian:13

# --- Variables
ENV DEBIAN_FRONTEND=noninteractive
ENV NThreads=4
ENV FAIRSOFT_VER=jan24p5

# --- Dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
        wget curl git gnupg ca-certificates \
        build-essential \
        autoconf automake binutils \
        bison bzip2 coreutils debianutils file findutils flex \
        g++ gcc gfortran gzip hostname make patch \
        python3 python3-pip python3-dev \
        sed subversion tar unzip xutils-dev xz-utils \
        pkg-config \
        clang clang-tidy clang-format \
        cmake ninja-build \
        libbz2-dev libcurl4-openssl-dev libgsl-dev libicu-dev \
        libfftw3-dev libprotobuf-dev protobuf-compiler-grpc \
        libgl1-mesa-dev libglu1-mesa-dev libgrpc++-dev \
        liblzma-dev libncurses-dev libreadline-dev libsqlite3-dev \
        libssl-dev libtool libx11-dev libxerces-c-dev \
        libxext-dev libxft-dev libxml2-dev libxmu-dev libxpm-dev \
        libyaml-cpp-dev libzstd-dev \
        libfuse-dev libfuse3-dev libcap-dev uuid-dev cpio \
        libgtest-dev libgmock-dev \
        valgrind ccache lsb-release mmdb-bin libmaxminddb0 libmaxminddb-dev \
        fuse && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# --- Configuration
RUN python3 -m pip config set global.break-system-packages true && \
    pip install -U setuptools

# --- Layer 5: Checks
RUN cmake --version

# --- CVMFS
RUN mkdir -p /misc && cd /misc && \
    git clone --depth 1 --branch devel https://github.com/cvmfs/cvmfs.git && \
    cd cvmfs && mkdir build && cd build && \
    cmake -GNinja .. && \
    ninja -j${NThreads} && \
    ninja install && \
    cd /misc && rm -rf cvmfs

# --- FairSoft
RUN cd /misc && \
    git clone --depth 1 --branch ${FAIRSOFT_VER} https://github.com/FairRootGroup/FairSoft.git FairSoft && \
    ./FairSoft/legacy/setup-debian.sh && \
    rm -rf FairSoft

# --- Configuration
CMD ["python3", "-m", "pip", "config", "set", "global.break-system-packages", "true"]

# --- Layer 6: Containers
LABEL org.opencontainers.image.title="cvmfs_clang"
LABEL org.opencontainers.image.authors="Jose Luis Rodriguez Sanchez <j.l.rodriguez.sanchez@udc.es>"
