# Imagen Ubuntu 25.04
FROM ubuntu:25.04

# --- Layer 2: Variables
ENV DEBIAN_FRONTEND=noninteractive
ENV NThreads=4
ENV FAIRSOFT_VER=jan24p5
ENV FAIRROOT_VER=v18.8.2
ENV FAIRSOFTPATH="/opt/FairSoft"
ENV FAIRROOTPATH="/opt/FairRoot"

# --- Layer 3: Dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
        -o Dpkg::Use-Pty=0 \
        -o APT::Sandbox::User=root \
        build-essential \
        cmake ninja-build \
        gfortran \
        git wget curl ca-certificates gnupg \
        python3 python3-pip python3-dev \
        pkg-config \
        autoconf automake libtool \
        bison flex \
        clang clang-tidy clang-format \
        libgsl-dev libfftw3-dev \
        libprotobuf-dev protobuf-compiler-grpc libgrpc++-dev \
        libgl1-mesa-dev libglu1-mesa-dev \
        libx11-dev libxext-dev libxft-dev libxmu-dev libxpm-dev libxerces-c-dev libxml2-dev \
        libreadline-dev libncurses-dev libbz2-dev liblzma-dev libzstd-dev libssl-dev \
        libyaml-cpp-dev \
        libfuse-dev libfuse3-dev libcap-dev uuid-dev cpio \
        valgrind ccache rsync subversion unzip xz-utils tar \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# --- Configuration
RUN python3 -m pip config set global.break-system-packages true && \
    pip install -U setuptools

# --- Conan
RUN python3 -m pip install conan

# --- FairSoft
RUN mkdir -p /misc && cd /misc && \
    git clone --depth 1 --branch ${FAIRSOFT_VER} https://github.com/FairRootGroup/FairSoft.git FairSoft && \
    ./FairSoft/legacy/setup-ubuntu.sh && \
    apt-get remove -y cmake && \
    ./FairSoft/bootstrap-cmake.sh /usr && \
    rm -rf FairSoft

# --- Layer 5: Checks
RUN cmake --version

# --- Configuration
CMD ["python3", "-m", "pip", "config", "set", "global.break-system-packages", "true"]

# --- Layer 6: Container
LABEL org.opencontainers.image.title="jan24p5_base"
LABEL org.opencontainers.image.authors="Jose Luis Rodriguez Sanchez <j.l.rodriguez.sanchez@udc.es>"

