# Imagen Ubuntu 24.04
FROM docker.io/r3bdockers/ubuntu2404_base:latest

# --- FairSoft
RUN mkdir -p /misc && cd /misc && \
    git clone --depth 1 --branch ${FAIRSOFT_VER} https://github.com/FairRootGroup/FairSoft.git FairSoft && \
    cd FairSoft && \
    mkdir -p $FAIRSOFTPATH && \
    mkdir -p build && \
    cmake -S ./ -B ./build -DCMAKE_INSTALL_PREFIX=$FAIRSOFTPATH -C ./FairSoftConfig.cmake && \
    cmake --build ./build -j${NThreads}
    cd .. && rm -rf FairSoft
    
# --- FairRoot
RUN cd /misc && \
    git clone --depth 1 --branch ${FAIRROOT_VER} https://github.com/FairRootGroup/FairRoot.git FairRoot && \
    cd FairRoot && git status && \
    mkdir -p $FAIRROOTPATH && \
    mkdir -p build && \
    export SIMPATH=$FAIRSOFTPATH
    cmake -S ./ -B ./build -DCMAKE_INSTALL_PREFIX=$FAIRROOTPATH && \
    cd build && make -j${NThreads} && make install && \
    cd ../.. && rm -rf FairRoot
 
# --- UCESB
RUN cd /opt && \   
    . $FAIRSOFTPATH/bin/thisroot.sh && \
    git clone https://git.chalmers.se/expsubphys/ucesb.git && \
    cd ucesb && make empty/empty -j${NThreads}

# --- CMake 4.0.3
RUN mkdir -p /opt && cd /opt && \
    wget https://github.com/Kitware/CMake/releases/download/v4.0.3/cmake-4.0.3.tar.gz && \
    tar -xzf cmake-4.0.3.tar.gz && cd cmake-4.0.3 && \
    ./bootstrap && make -j${NThreads} && make install && \
    cd / && rm -rf /opt/cmake-4.0.3*

# --- Layer 5: Checks
RUN cmake --version

# --- Configuration
CMD ["python3", "-m", "pip", "config", "set", "global.break-system-packages", "true"]

# --- Layer 6: Container
LABEL org.opencontainers.image.title="jan24p5_v18.8.2"
LABEL org.opencontainers.image.authors="Jose Luis Rodriguez Sanchez <j.l.rodriguez.sanchez@udc.es>"

