# --- Imagen base
FROM debian:12

# --- Variables
ENV DEBIAN_FRONTEND=noninteractive
ENV NThreads=4
ENV FAIRSOFT_VER=jan24p5
ENV FAIRROOT_VER=v18.8.2
ENV FAIRSOFTPATH="/opt/FairSoft"
ENV FAIRROOTPATH="/opt/FairRoot"

# --- Layer 3: Dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
        wget curl git gnupg ca-certificates \
        build-essential \
        autoconf automake binutils \
        bison bzip2 coreutils debianutils file findutils flex \
        g++ gcc gfortran gzip hostname make patch \
        python3 python3-pip python3-dev \
        sed subversion tar unzip xutils-dev xz-utils \
        pkg-config \
        clang clang-tidy clang-format \
        cmake ninja-build \
        libbz2-dev libcurl4-openssl-dev libgsl-dev libicu-dev \
        libfftw3-dev libprotobuf-dev protobuf-compiler-grpc \
        libgl1-mesa-dev libglu1-mesa-dev libgrpc++-dev \
        liblzma-dev libncurses-dev libreadline-dev libsqlite3-dev \
        libssl-dev libtool libx11-dev libxerces-c-dev \
        libxext-dev libxft-dev libxml2-dev libxmu-dev libxpm-dev \
        libyaml-cpp-dev libzstd-dev \
        libfuse-dev libfuse3-dev libcap-dev uuid-dev cpio \
        libgtest-dev libgmock-dev \
        valgrind ccache lsb-release mmdb-bin libmaxminddb0 libmaxminddb-dev \
        fuse && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# --- Configuration
RUN python3 -m pip config set global.break-system-packages true && \
    pip install -U setuptools

# --- Conan
RUN python3 -m pip install conan

# --- FairSoft
RUN mkdir -p /misc && cd /misc && \
    git clone --depth 1 --branch ${FAIRSOFT_VER} https://github.com/FairRootGroup/FairSoft.git FairSoft && \
    ./FairSoft/legacy/setup-debian.sh && \
    apt-get remove -y cmake && \
    ./FairSoft/bootstrap-cmake.sh /usr && \
    rm -rf FairSoft

# --- Layer 5: Checks
RUN cmake --version

# --- Configuration
CMD ["python3", "-m", "pip", "config", "set", "global.break-system-packages", "true"]

# --- Layer 6: Containers
LABEL org.opencontainers.image.title="jan24p5_base"
LABEL org.opencontainers.image.authors="Jose Luis Rodriguez Sanchez <j.l.rodriguez.sanchez@udc.es>"
